export enum weatherEnum {
	SUN = 'sun',
	SEMI_CLEAR = 'semi-clear',
	OVERCAST = 'overcast',
	FOG = 'fog',
	RAIN_SHOWER = 'rain-shower',
	RAIN = 'rain',
	SNOWFALL = 'snowfall',
	SNOW_SHOWER = 'snow-shower',
	THUNDER = 'thunder',
	SNOWY_RAIN = 'snowy-rain',
	HAIL = 'hail',
	// SUN = 'Sol',
	// SEMI_CLEAR = 'Halvklart',
	// OVERCAST = 'Mulet',
	// FOG = 'Dimma',
	// RAIN_SHOWER = 'Regnskur',
	// RAIN = 'Regn',
	// SNOWFALL = 'Snöfall',
	// SNOW_SHOWER = 'Snöby',
	// THUNDER = 'Åska',
	// SNOWY_RAIN = 'Snöblandat regn',
	// HAIL = 'Hagel',
}

export default weatherEnum;
