GET http://localhost:5000/api/logs/

###

POST http://localhost:5000/api/logs/register 
Content-Type: application/json

{
    "airFeeling": "Skylig,",
    "airpressure": "1024",
    "description": "Vädret har varit växlande med lite regnskurar",
    "date": "205212",
    "humidity": "64",
    "precipitation": "4",
    "temperature": "14",
    "windDirection": "nw",
    "weather": "clear",
    "windSpeed": "2"
}

### 

PUT http://localhost:5000/api/logs/61bba11c4b2c4ac56f05e2da
Content-Type: application/json

{
    "airFeeling": "Varmt",
    "airpressure": "950",
    "description": "Regnar hela dagen!",
    "date": "211214",
    "humidity": "64",
    "precipitation": "4",
    "temperature": "14",
    "windDirection": "nw",
    "weather": "clear",
    "windSpeed": "2"
}

###

DELETE http://localhost:5000/api/logs/61bba11c4b2c4ac56f05e2da
