GET http://localhost:5000/api/logs/

###
GET http://localhost:5000/api/home/

###

GET http://localhost:5000/api/log/20220120

###

GET http://localhost:5000/api/diagram/202201

###

POST http://localhost:5000/api/logs/register 
Content-Type: application/json

{
    "airFeeling": "Skylig,",
    "airpressure": "1024",
    "description": "Vädret har varit växlande med lite regnskurar",
    "date": "2022001",
    "humidity": "64",
    "precipitation": "4",
    "temperature": "14",
    "windDirection": "nw",
    "weather": "clear",
    "windSpeed": "2"
}

### 

PUT http://localhost:5000/api/logs/61e960d8b51fc5555c5c17c5
Content-Type: application/json

{
    "airFeeling": "Varmt",
    "airpressure": "950",
    "description": "Regnar hela dagen!",
    "humidity": "64",
    "precipitation": "4",
    "temperature": "14",
    "windDirection": "nw",
    "weather": "clear",
    "windSpeed": "2"
}

###

DELETE http://localhost:5000/api/logs/61e960cab51fc5555c5c17c1
