GET http://localhost:5000/api/user/

###

POST http://localhost:5000/api/user/register 
Content-Type: application/json

{
    "email": "a@a.se",
    "password": "123456"
}
###

POST http://localhost:5000/api/user/addUserInfo
Content-Type: application/json

{
    "firstName": "Hans",
    "lastName": "Gustavsson",
    "city": "Göteborg"
}

###

POST http://localhost:5000/api/user/login 
Content-Type: application/json

{
"email": "a@a.se",
 "password": "654321"
}

###

PUT http://localhost:5000/api/user/edit/ 
Content-Type: application/json

{
    "firstName": "Nils",
    "lastName": "Hansson",
    "city": "Halmstad"
}
###

PUT http://localhost:5000/api/user/changePassword 
Content-Type: application/json

{
    "oldPassword": "1236",
    "newPassword": "1235"
}

###

POST http://localhost:5000/api/user/logout

###

DELETE http://localhost:5000/api/user/delete