GET http://localhost:5000/api/users/

###

POST http://localhost:5000/api/user/register 
Content-Type: application/json

{
    "email": "hans@telia.se",
    "password": "123",
    "firstName": "Hans",
    "lastName": "Gustavsson",
    "city": "Göteborg"
}

###

POST http://localhost:5000/api/user/login 
Content-Type: application/json

{
"email": "hans@telia.se", "password": "1234"
}

###

PUT http://localhost:5000/api/user/edit/ 
Content-Type: application/json

{
    "firstName": "Nils",
    "lastName": "Hansson",
    "city": "Halmstad"
}
###

PUT http://localhost:5000/api/user/changePassword 
Content-Type: application/json

{
    "oldPassword": "123",
    "newPassword": "1234"
}

###

POST http://localhost:5000/api/user/logout

###

DELETE http://localhost:5000/api/user/delete